# Use official Tomcat image with Java 11
FROM tomcat:9.0-jdk11

# Remove default webapps to keep container clean (optional)
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR file generated by Maven into Tomcat webapps folder
# Make sure the WAR filename matches the one Maven produces
COPY target/my-java-project-1.0.0-SNAPSHOT-shaded.war /usr/local/tomcat/webapps/my-java-project.war

# Expose Tomcat default port
EXPOSE 8080

# Start Tomcat server
CMD ["catalina.sh", "run"]
