# Use official Tomcat image with Java 21
FROM tomcat:10.1-jdk21

# Remove default webapps to keep container clean
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR file generated by Maven into Tomcat webapps folder
# This must match the shaded WAR Maven produces
COPY target/my-java-project-1.0.0-SNAPSHOT-shaded.war /usr/local/tomcat/webapps/my-java-project.war

# Expose Tomcat default port
EXPOSE 8080

# Start Tomcat server
CMD ["catalina.sh", "run"]
